PitchTuner: src/PitchTracker/AutomaticGainControl_test.cc File Reference
AutomaticGainControl_test.cc File Reference
#include <vector>
#include <iostream>
#include <sstream>
#include <algorithm>
#include "saSample.h"
#include "saInputFileSelector.h"
#include "saInputSource.h"
#include "saInputFileWav.h"
#include "saInputStream.h"
#include "saOutputFileSelector.h"
#include "saOutputSink.h"
#include "saOutputStream.h"
#include "saOutputFileWav.h"
#include "AutomaticGainControl.h"
#include "ButterworthFilter.h"
Functions
static void Usage ()
void ParseOptions (int argc, char *argv[], bool &helpReq, bool &debugReq, std::size_t &seconds, std::string &inFileName, std::string &outFileName, float &lpFilterCutoff, float &hpFilterCutoff, std::size_t &fastTauMs, std::size_t &slowTauMs, std::size_t &peakTauMs, float &lowerPeakThreshold, float &upperPeakThreshold, float &gainMin, float &gainMax)
int main (int argc, char *argv[])
Function Documentation
Usage()
static void Usage () static
Definition at line 31 of file AutomaticGainControl_test.cc.
Referenced by ParseOptions().
ParseOptions()
void ParseOptions (int argc, char * argv[], bool & helpReq, bool & debugReq, std::size_t & seconds, std::string & inFileName, std::string & outFileName, float & lpFilterCutoff, float & hpFilterCutoff, std::size_t & fastTauMs, std::size_t & slowTauMs, std::size_t & peakTauMs, float & lowerPeakThreshold, float & upperPeakThreshold, float & gainMin, float & gainMax)
Definition at line 65 of file AutomaticGainControl_test.cc.
References Usage().
Referenced by main(), and PitchTuner::OnInit().
main()
int main (int argc, char * argv[])
Definition at line 183 of file AutomaticGainControl_test.cc.
References ParseOptions(), SimpleAudio::saInputSourceOpenFileWav(), SimpleAudio::saInputStreamOpenFile(), SimpleAudio::saOutputSinkOpenFileWav(), and SimpleAudio::saOutputStreamOpenFile().