PitchTuner: src/PitchTracker/ButterworthFilter.h File Reference
ButterworthFilter.h File Reference
Implemetation of Butterworth filters as a cascade of second-order state-space sections.
#include <memory>
#include <numbers>
#include <cmath>
#include "Filter.h"
#include "saSample.h"
Data Structures
struct _pqd_t
struct _Abcd_t
class StateVariable2ndOrderSection< T >
Representation of a second order state-variable filter.
class StateVariable1stOrderSection< T >
Representation of a first order state-variable filter.
class ButterworthHighPass2ndOrderFilter< T >
Implementation of a Butterworth second order state-variable high pass filter.
class ButterworthLowPass4thOrderFilter< T >
Implementation of a Butterworth fourth order state-variable low pass filter as the cascade of two second order low noise state variable filter sections.
class ButterworthHighPass3rdOrderFilter< T >
Implementation of a Butterworth third order state-variable high pass filter as the parallel sum of Gray and Markel second order and first order allpass filters.
class ButterworthHighPassStoyanov3rdOrderFilter< T >
Implementation of a Butterworth third order state-variable high pass filter as the parallel sum of Stoyanov second order and first order allpass filters.
Typedefs
typedef struct _pqd_t pqd_t
typedef struct _Abcd_t Abcd_t
Functions
static void HighPassButterworthWcThetaToPqd (const float wc, const float theta, pqd_t &pqd)
static void LowPassButterworthWcThetaToPqd (const float wc, const float theta, pqd_t &pqd)
static void PqdToLowNoiseAbcd (const pqd_t pqd, Abcd_t &Abcd)
Detailed Description
Implemetation of Butterworth filters as a cascade of second-order state-space sections.
This file implements Butterworth second- and third-order high-pass filters and a Butterworth fourth-order low-pass filter as a cascade of low-noise second-order state-variable sections or as the parallel combination of two all-pass state-variable sections.
For a low-pass Butterworth filter, the squared magnitude response is [1] :
\[ \left|\hat{H}(s)\right|^{2} = \frac{1}{1+\omega^{2n}} \]
The \(2n\) poles of the Butterworth squared-magnitude response are evenly spaced around a circle in the \(s\)-plane. In the left half \(s\)-plane the angles are:
\[ \theta_{k}=\frac{\pi}{2}\left(1+\frac{2k-1}{n}\right)\;,\quad 1\le k\le n \]
If the cutoff frequency in the \(s\)-plane is \(\omega_{c}\) then first order low-pass sections are:
\[ \frac{\omega_{c}}{s+\omega_{c}} \]
and second order low-pass sections are:
\[ \frac{\omega_{c}^{2}}{s^{2}-2\omega_{c}\cos\theta_{k}s+\omega_{c}^{2}} \]
The \(s\)-plane Butterworth response is transformed to the \(z\)-plane by:
\[ H(z) = \hat{H}\left(\frac{1-z^{-1}}{1+z^{-1}}\right) \]
On the \(z\)-plane unit circle, \(z=e^{\imath\Omega T}\), where \(T\) is the sampling interval and:
\[ H(e^{\imath\Omega T}) = \hat{H}\left(\imath\tan\frac{\Omega T}{2}\right) \]
For each filter, first find the Butterworth pole locations and the corresponding transfer function for each second-order section:
\[ H(z)=d+\frac{q_1 z^{-1} + q_2 z^{-2}}{1 + p_1 z^{-1} + p_2 z^{-2}} \]
Next, find the optimal low-noise second order state variable sections [2] or, for high-pass filters the Stoyanov [3] LS1 and LS2a, or Gray-and-Markel [4] GM1 and GM2, first and second order state variable sections. The Stoyanov and Gray-and-Markel all-pass filters are "structurally lossless" in the sense of Vaidyanathan et al. [5] ; the all-pass response is retained when the coefficients are truncated.
See:
[1] Appendix 6A, "Design of Analog Filter Prototypes", in "Digital Signal Processing", R. A. Roberts and C. T. Mullis, Addison-Wesley, 1987, ISBN 0-201-16350-0
[2] "New second-order state-space structures for realizing low round off noise digital filters", B. W. Bomar, IEEE Transactions on Acoustics, Speech and Signal Processing, Vol. ASSP-33, pp. 106-110, Feb. 1985
[3] "Design and Realization of Efficient IIR Digital Filter Structures Based on Sensitivity Minimizations", G. Stoyanov, Z. Nikolova, K. Ivanova and V. Anzova, Proceedings TELSIKS 2007, pp. 299-308, Sept. 2007
[4] "Digital Lattice And Ladder Filter Synthesis", A. H. Gray and J. D. Markel, IEEE Transactions on Audio and Electroacoustics, Vol. 21, No. 6, pp. 491-500, Dec. 1973
[5] "A New Approach to the Realization of Low-Sensitivity IIR Digital Filters", P. P. Vaidyanathan,S. K. Mitra and Y. Nuevo, IEEE Transactions on Acoustics, Speech and Signal Processing, Vol. ASSP-34, No. 2, pp. 350-361, April 1986
Testing with Octave
Create a noise sequence in Octave:
Fs = 48000
N = Fs*10
n = rand(N,1)-0.5;
n = 0.5*n/std(n);
audiowrite('noise.wav',n,Fs);
Run Butterworth_test:
bin/ButterworthFilter_test --inFile noise.wav --outFile y.wav
                           --seconds 10 --cutoff 100 --high_pass_GM
Analyse the result in Octave:
[y,Fs]=audioread('y.wav');
Nfreq=16384
td=xspec(n,y,2*Nfreq);
plot((0:(Nfreq-1))*Fs/(2*Nfreq), 20*log10(abs(td(1:Nfreq))))
axis([0 200 -50 5]);
Definition in file ButterworthFilter.h.
Typedef Documentation
pqd_t
typedef struct _pqd_t pqd_t
Abcd_t
typedef struct _Abcd_t Abcd_t
Function Documentation
HighPassButterworthWcThetaToPqd()
static void HighPassButterworthWcThetaToPqd (const float wc, const float theta, pqd_t & pqd) inline static
Utility function to convert the wc and theta specification of a second order Butterworth high-pass filter to pdq_t format
Definition at line 138 of file ButterworthFilter.h.
Referenced by ButterworthHighPass2ndOrderFilter< T >::ButterworthHighPass2ndOrderFilter().
LowPassButterworthWcThetaToPqd()
static void LowPassButterworthWcThetaToPqd (const float wc, const float theta, pqd_t & pqd) static
Utility function to convert the wc and theta specification of a second order Butterworth low-pass filter to pdq_t format
Definition at line 155 of file ButterworthFilter.h.
Referenced by ButterworthLowPass4thOrderFilter< T >::ButterworthLowPass4thOrderFilter().
PqdToLowNoiseAbcd()
static void PqdToLowNoiseAbcd (const pqd_t pqd, Abcd_t & Abcd) static
Utility function to convert the pdq_t specification of a second order filter to low-noise Abcd_t format
Definition at line 172 of file ButterworthFilter.h.
References _pqd_t::d, _pqd_t::p1, _pqd_t::p2, _pqd_t::q1, and _pqd_t::q2.
Referenced by ButterworthHighPass2ndOrderFilter< T >::ButterworthHighPass2ndOrderFilter(), and ButterworthLowPass4thOrderFilter< T >::ButterworthLowPass4thOrderFilter().