PitchTuner: src/PitchTracker/ButterworthFilter_test.cc File Reference
ButterworthFilter_test.cc File Reference
#include <vector>
#include <iostream>
#include <sstream>
#include <algorithm>
#include "saSample.h"
#include "saInputFileSelector.h"
#include "saInputSource.h"
#include "saInputFileWav.h"
#include "saInputStream.h"
#include "saOutputFileSelector.h"
#include "saOutputSink.h"
#include "saOutputStream.h"
#include "saOutputFileWav.h"
#include "ButterworthFilter.h"
Functions
static void Usage ()
void ParseOptions (int argc, char *argv[], bool &helpReq, bool &high_pass_LN, bool &high_pass_GM, bool &high_pass_LS, std::size_t &seconds, float &cutoff, std::string &inFileName, std::string &outFileName)
int main (int argc, char *argv[])
Function Documentation
Usage()
static void Usage () static
Definition at line 22 of file ButterworthFilter_test.cc.
Referenced by ParseOptions().
ParseOptions()
void ParseOptions (int argc, char * argv[], bool & helpReq, bool & high_pass_LN, bool & high_pass_GM, bool & high_pass_LS, std::size_t & seconds, float & cutoff, std::string & inFileName, std::string & outFileName)
Definition at line 44 of file ButterworthFilter_test.cc.
References Usage().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 126 of file ButterworthFilter_test.cc.
References ParseOptions(), SimpleAudio::saInputSourceOpenFileWav(), SimpleAudio::saInputStreamOpenFile(), SimpleAudio::saOutputSinkOpenFileWav(), and SimpleAudio::saOutputStreamOpenFile().