PitchTuner: saSampleBase< T, L, S, O, U > Class Template Reference
saSampleBase< T, L, S, O, U > Class Template Reference
A class for audio samples.
#include <saSampleBase.h>
Public Member Functions
~saSampleBase () throw ()
saSampleBase ()
Default constructor.
saSampleBase (const saSampleBase &a)
saSampleBase (const int16_t value)
saSampleBase (const uint16_t value)
saSampleBase (const int32_t value)
saSampleBase (const uint32_t value)
saSampleBase (int64_t value)
saSampleBase (size_t value)
saSampleBase (float value)
saSampleBase (double value)
template<typename NewType >
NewType to () const
template<typename saDeviceType >
saDeviceType toSink () const
template<typename saDeviceType >
void fromSource (const saDeviceType s)
T Get () const
saSampleBase operator* ()
saSampleBase * operator& ()
saSampleBase operator- ()
saSampleBase & operator= (const saSampleBase &rhs)
saSampleBase operator+= (const saSampleBase &rhs)
saSampleBase operator-= (const saSampleBase &rhs)
saSampleBase operator*= (const saSampleBase &rhs)
saSampleBase operator/= (const saSampleBase &rhs)
bool operator== (const saSampleBase &rhs) const
bool operator< (const saSampleBase &rhs) const
bool operator!= (const saSampleBase< T, L, S, O, U > &rhs)
bool operator> (const saSampleBase< T, L, S, O, U > &rhs)
bool operator>= (const saSampleBase< T, L, S, O, U > &rhs)
bool operator<= (const saSampleBase< T, L, S, O, U > &rhs)
Static Public Attributes
static constexpr size_t saInternalNumBits = std::numeric_limits<T>::digits
static constexpr L saInternalMax
static constexpr L saInternalMin
If T is floating point then std::numeric_limits<T>::min() is ~ 1e-38.
static constexpr size_t saInternalBinaryPoint = 15
static constexpr T saInternalOne = static_cast<T>(1<<saInternalBinaryPoint)
static constexpr L saInputMax = saInternalMax/static_cast<L>(saInternalOne)
static constexpr L saInputMin = saInternalMin/static_cast<L>(saInternalOne)
Private Member Functions
void CompileTimeAssertions ()
Compile-time assertions.
template<typename C >
void CheckResult (C value, L &result)
Private utility functions.
T ABonC (T const a, T const b, T const c)
Private Attributes
T sample
The sample!
Detailed Description
template<typename T, typename L, bool S, bool O, bool U>
class SimpleAudio::saSampleBase< T, L, S, O, U >
A class for audio samples.
Template Parameters
Stored type
Internal long type
Saturate on overflow
Overflow causes exception
Underflow causes exception
Definition at line 80 of file saSampleBase.h.
Constructor & Destructor Documentation
~saSampleBase()
template<typename T , typename L , bool S, bool O, bool U> ~saSampleBase () throw () inline
Definition at line 120 of file saSampleBase.h.
saSampleBase() [1/10]
template<typename T , typename L , bool S, bool O, bool U> saSampleBase () inline
Default constructor.
Definition at line 123 of file saSampleBase.h.
saSampleBase() [2/10]
template<typename T , typename L , bool S, bool O, bool U> saSampleBase (const saSampleBase< T, L, S, O, U > & a) inline
Constructor
Parameters
a initial value
Definition at line 127 of file saSampleBase.h.
saSampleBase() [3/10]
template<typename T , typename L , bool S, bool O, bool U> saSampleBase (const int16_t value) inline
Cnstructor
Parameters
value int16_t initial value
Definition at line 131 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::saInternalOne, and saSampleBase< T, L, S, O, U >::sample.
saSampleBase() [4/10]
template<typename T , typename L , bool S, bool O, bool U> saSampleBase (const uint16_t value) inline
Cnstructor
Parameters
value uint16_t initial value
Definition at line 141 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::saInternalOne, and saSampleBase< T, L, S, O, U >::sample.
saSampleBase() [5/10]
template<typename T , typename L , bool S, bool O, bool U> saSampleBase (const int32_t value) inline
Cnstructor
Parameters
value int32_t initial value
Definition at line 151 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::saInternalOne, and saSampleBase< T, L, S, O, U >::sample.
saSampleBase() [6/10]
template<typename T , typename L , bool S, bool O, bool U> saSampleBase (const uint32_t value) inline
Cnstructor
Parameters
value uint32_t initial value
Definition at line 161 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::saInternalOne, and saSampleBase< T, L, S, O, U >::sample.
saSampleBase() [7/10]
template<typename T , typename L , bool S, bool O, bool U> saSampleBase (int64_t value) inline
Cnstructor
Parameters
value int64_t initial value
Definition at line 171 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::saInputMax, saSampleBase< T, L, S, O, U >::saInputMin, saSampleBase< T, L, S, O, U >::saInternalMax, saSampleBase< T, L, S, O, U >::saInternalMin, saSampleBase< T, L, S, O, U >::saInternalOne, and saSampleBase< T, L, S, O, U >::sample.
saSampleBase() [8/10]
template<typename T , typename L , bool S, bool O, bool U> saSampleBase (size_t value) inline
Cnstructor
Parameters
value uint64_t initial value
Definition at line 203 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::saInputMax, saSampleBase< T, L, S, O, U >::saInternalMax, saSampleBase< T, L, S, O, U >::saInternalOne, and saSampleBase< T, L, S, O, U >::sample.
saSampleBase() [9/10]
template<typename T , typename L , bool S, bool O, bool U> saSampleBase (float value) inline
Cnstructor
Parameters
value float initial value
Definition at line 229 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::saInputMax, saSampleBase< T, L, S, O, U >::saInputMin, saSampleBase< T, L, S, O, U >::saInternalMax, saSampleBase< T, L, S, O, U >::saInternalMin, saSampleBase< T, L, S, O, U >::saInternalOne, and saSampleBase< T, L, S, O, U >::sample.
saSampleBase() [10/10]
template<typename T , typename L , bool S, bool O, bool U> saSampleBase (double value) inline
Cnstructor
Parameters
value double initial value
Definition at line 263 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::saInputMax, saSampleBase< T, L, S, O, U >::saInputMin, saSampleBase< T, L, S, O, U >::saInternalMax, saSampleBase< T, L, S, O, U >::saInternalMin, saSampleBase< T, L, S, O, U >::saInternalOne, and saSampleBase< T, L, S, O, U >::sample.
Member Function Documentation
CompileTimeAssertions()
template<typename T , typename L , bool S, bool O, bool U> void CompileTimeAssertions () inline private
Compile-time assertions.
Definition at line 87 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::saInternalBinaryPoint.
to()
template<typename T , typename L , bool S, bool O, bool U> template<typename NewType > NewType to () const inline
Conversion from saSampleBase
Template Parameters
NewType convert saSampleBase to NewType
Returns
converted value
Definition at line 295 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::saInternalMax, saSampleBase< T, L, S, O, U >::saInternalMin, saSampleBase< T, L, S, O, U >::saInternalOne, and saSampleBase< T, L, S, O, U >::sample.
Referenced by saSampleTo< C >::operator()(), saSampleTestTo< S >::operator()(), SimpleAudio::operator<<(), and SimpleAudio::operator<<().
toSink()
template<typename T , typename L , bool S, bool O, bool U> template<typename saDeviceType > saDeviceType toSink () const inline
Conversion from saSampleBase to saDeviceType
Template Parameters
saDeviceType typename of input type
Returns
converted value
Definition at line 355 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::saInternalBinaryPoint, saSampleBase< T, L, S, O, U >::saInternalOne, and saSampleBase< T, L, S, O, U >::sample.
Referenced by saSampleToSink< saDeviceType >::operator()().
fromSource()
template<typename T , typename L , bool S, bool O, bool U> template<typename saDeviceType > void fromSource (const saDeviceType s) inline
Conversion from saDeviceType to saSampleBase
Template Parameters
saDeviceType typename of input type
Parameters
s input value
Definition at line 400 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::saInternalBinaryPoint, and saSampleBase< T, L, S, O, U >::sample.
Referenced by saSampleFromSource< saDeviceType >::operator()().
Get()
template<typename T , typename L , bool S, bool O, bool U> T Get () const inline
Peek at internal values
Returns
saSampleBase internal value
Definition at line 426 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::sample.
operator*()
template<typename T , typename L , bool S, bool O, bool U> saSampleBase operator* () inline
Definition at line 429 of file saSampleBase.h.
operator&()
template<typename T , typename L , bool S, bool O, bool U> saSampleBase * operator& () inline
Definition at line 431 of file saSampleBase.h.
operator-()
template<typename T , typename L , bool S, bool O, bool U> saSampleBase operator- () inline
Definition at line 433 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::sample.
operator=()
template<typename T , typename L , bool S, bool O, bool U> saSampleBase & operator= (const saSampleBase< T, L, S, O, U > & rhs) inline
Definition at line 445 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::sample.
operator+=()
template<typename T , typename L , bool S, bool O, bool U> saSampleBase operator+= (const saSampleBase< T, L, S, O, U > & rhs) inline
Definition at line 451 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::sample.
operator-=()
template<typename T , typename L , bool S, bool O, bool U> saSampleBase operator-= (const saSampleBase< T, L, S, O, U > & rhs) inline
Definition at line 459 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::sample.
operator*=()
template<typename T , typename L , bool S, bool O, bool U> saSampleBase operator*= (const saSampleBase< T, L, S, O, U > & rhs) inline
Definition at line 467 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::ABonC(), saSampleBase< T, L, S, O, U >::saInternalOne, and saSampleBase< T, L, S, O, U >::sample.
operator/=()
template<typename T , typename L , bool S, bool O, bool U> saSampleBase operator/= (const saSampleBase< T, L, S, O, U > & rhs) inline
Definition at line 473 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::ABonC(), saSampleBase< T, L, S, O, U >::saInternalOne, and saSampleBase< T, L, S, O, U >::sample.
operator==()
template<typename T , typename L , bool S, bool O, bool U> bool operator== (const saSampleBase< T, L, S, O, U > & rhs) const inline
Definition at line 479 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::sample.
operator<()
template<typename T , typename L , bool S, bool O, bool U> bool operator< (const saSampleBase< T, L, S, O, U > & rhs) const inline
Definition at line 484 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::sample.
operator!=()
template<typename T , typename L , bool S, bool O, bool U> bool operator!= (const saSampleBase< T, L, S, O, U > & rhs) inline
Definition at line 489 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::sample.
operator>()
template<typename T , typename L , bool S, bool O, bool U> bool operator> (const saSampleBase< T, L, S, O, U > & rhs) inline
Definition at line 494 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::sample.
operator>=()
template<typename T , typename L , bool S, bool O, bool U> bool operator>= (const saSampleBase< T, L, S, O, U > & rhs) inline
Definition at line 499 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::sample.
operator<=()
template<typename T , typename L , bool S, bool O, bool U> bool operator<= (const saSampleBase< T, L, S, O, U > & rhs) inline
Definition at line 504 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::sample.
CheckResult()
template<typename T , typename L , bool S, bool O, bool U> template<typename C > void CheckResult (C value, L & result) inline private
Private utility functions.
Check the result for saturation, overflow and underflow
Template Parameters
C typename of input value
Parameters
value input value
result result to be checked
Definition at line 517 of file saSampleBase.h.
References saSampleBase< T, L, S, O, U >::saInternalMax, and saSampleBase< T, L, S, O, U >::saInternalMin.
ABonC()
template<typename T , typename L , bool S, bool O, bool U> T ABonC (T const a, T const b, T const c) inline private
Definition at line 542 of file saSampleBase.h.
Referenced by saSampleBase< T, L, S, O, U >::operator*=(), and saSampleBase< T, L, S, O, U >::operator/=().
Field Documentation
sample
template<typename T , typename L , bool S, bool O, bool U> T sample private
The sample!
Definition at line 84 of file saSampleBase.h.
Referenced by saSampleBase< T, L, S, O, U >::fromSource(), saSampleBase< T, L, S, O, U >::Get(), saSampleBase< T, L, S, O, U >::operator!=(), saSampleBase< T, L, S, O, U >::operator*=(), saSampleBase< T, L, S, O, U >::operator+=(), saSampleBase< T, L, S, O, U >::operator-(), saSampleBase< T, L, S, O, U >::operator-=(), saSampleBase< T, L, S, O, U >::operator/=(), saSampleBase< T, L, S, O, U >::operator<(), saSampleBase< T, L, S, O, U >::operator<=(), saSampleBase< T, L, S, O, U >::operator=(), saSampleBase< T, L, S, O, U >::operator==(), saSampleBase< T, L, S, O, U >::operator>(), saSampleBase< T, L, S, O, U >::operator>=(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::to(), and saSampleBase< T, L, S, O, U >::toSink().
saInternalNumBits
template<typename T , typename L , bool S, bool O, bool U> constexpr size_t saInternalNumBits = std::numeric_limits<T>::digits static constexpr
Definition at line 108 of file saSampleBase.h.
saInternalMax
template<typename T , typename L , bool S, bool O, bool U> constexpr L saInternalMax static constexpr
Initial value:
=
      static_cast<L>(std::numeric_limits<T>::max())
Definition at line 109 of file saSampleBase.h.
Referenced by saSampleBase< T, L, S, O, U >::CheckResult(), main(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), and saSampleBase< T, L, S, O, U >::to().
saInternalMin
template<typename T , typename L , bool S, bool O, bool U> constexpr L saInternalMin static constexpr
Initial value:
= std::is_integral<T>() ?
      static_cast<L>(std::numeric_limits<T>::min()) : -saInternalMax
If T is floating point then std::numeric_limits<T>::min() is ~ 1e-38.
Definition at line 112 of file saSampleBase.h.
Referenced by saSampleBase< T, L, S, O, U >::CheckResult(), main(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), and saSampleBase< T, L, S, O, U >::to().
saInternalBinaryPoint
template<typename T , typename L , bool S, bool O, bool U> constexpr size_t saInternalBinaryPoint = 15 static constexpr
Definition at line 114 of file saSampleBase.h.
Referenced by saSampleBase< T, L, S, O, U >::CompileTimeAssertions(), saSampleBase< T, L, S, O, U >::fromSource(), and saSampleBase< T, L, S, O, U >::toSink().
saInternalOne
template<typename T , typename L , bool S, bool O, bool U> constexpr T saInternalOne = static_cast<T>(1<<saInternalBinaryPoint) static constexpr
Definition at line 115 of file saSampleBase.h.
Referenced by main(), saSampleBase< T, L, S, O, U >::operator*=(), saSampleBase< T, L, S, O, U >::operator/=(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::to(), and saSampleBase< T, L, S, O, U >::toSink().
saInputMax
template<typename T , typename L , bool S, bool O, bool U> constexpr L saInputMax = saInternalMax/static_cast<L>(saInternalOne) static constexpr
Definition at line 116 of file saSampleBase.h.
Referenced by main(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), and saSampleBase< T, L, S, O, U >::saSampleBase().
saInputMin
template<typename T , typename L , bool S, bool O, bool U> constexpr L saInputMin = saInternalMin/static_cast<L>(saInternalOne) static constexpr
Definition at line 117 of file saSampleBase.h.
Referenced by main(), saSampleBase< T, L, S, O, U >::saSampleBase(), saSampleBase< T, L, S, O, U >::saSampleBase(), and saSampleBase< T, L, S, O, U >::saSampleBase().
The documentation for this class was generated from the following file:
src/SimpleAudio/saSampleBase.h