PitchTuner: PitchTunerFrame Class Reference
PitchTunerFrame Class Reference
#include <PitchTunerFrame.h>
Public Member Functions
PitchTunerFrame (wxString fileName, wxString deviceName, float sampleRate, std::size_t channel, std::size_t msLatency, std::size_t subSample, float inputLpFilterCutoff, float baseLineHpFilterCutoff, bool disableHpFilter, bool disableAgc, std::size_t msWindow, std::size_t msTmax, std::size_t msTsample, float threshold, bool removeDC, float A4Frequency, wxSize frameSize, bool guiTest, bool debug)
Constructor.
~PitchTunerFrame () throw ()
Private Member Functions
void * Entry ()
Pitch estimation thread entry function called by wxThreadHelper.
PitchTunerFrame & operator= (const PitchTunerFrame &)
Disallow assignment to PitchTunerFrame.
PitchTunerFrame (const PitchTunerFrame &)
Disallow copy constructor of PitchTunerFrame.
void OnDeviceOptions (wxCommandEvent &)
Device s menu item selected. Show the "Device Options" dialog box.
void OnAbout (wxCommandEvent &)
About menu item selected. Show the "about" message box.
void OnQuit (wxCommandEvent &)
Quit menu item selected.
void OnPitch (wxCommandEvent &)
A new pitch estimate is available. Update the GUI.
void OnEndOfStream (wxCommandEvent &)
End of stream event found on file or device.
void OnThreadError (wxCommandEvent &)
Error in the pitch estimation thread.
void OnClose (wxCloseEvent &)
Close button on frame selected.
void OnGuiTest (wxTimerEvent &)
void CreateGui ()
Create the wxWidgets GUI elements: meter graphic, option menu and dialog.
void UpdateGui ()
Draw the wxWidgets GUI.
bool FindAudioDevices ()
Interrogate the sound system and create a list of audio devices.
void RunThread ()
Run the pitch estimation algorithm in a separate thread.
void StopThread ()
Stop the pitch estimation thread.
void HandleError (const wxString)
Show an error message string on a message box.
Private Attributes
wxString m_fileName
Read audio waveform from this file.
wxString m_deviceName
Read audio waveform from this device.
float m_sampleRate
Audio input device sample rate.
std::size_t m_deviceLatencyMs
Audio device input buffer storage in ms.
std::size_t m_channel
Audio input device channel.
std::size_t m_subSample
Subsample the audio waveform after lowpass filtering.
float m_inputLpFilterCutoff
Low pass filter cutoff frequency.
float m_baseLineHpFilterCutoff
High pass filter cutoff frequency.
bool m_disableHpFilter
Disable the high pass filter.
bool m_disableAgc
Disable the pre-processor AGC.
std::size_t m_msWindow
Window width for correlation.
std::size_t m_msTmax
Maximum lag time for correlation.
std::size_t m_msTsample
Interval between pitch estimates.
float m_threshold
Maximum threshold for the difference function.
bool m_removeDC
Remove DC value from correlation.
int m_A4Frequency
Nominal A4 frequency.
bool m_guiTest
Enable GUI debugging with a fake pitch estimate.
bool m_debug
Store debugging information.
bool m_deviceFound
Device found.
int m_A4FrequencyLower
Meter lower valid A4 frequency.
int m_A4FrequencyUpper
Meter upper valid A4 frequency.
float m_frequency
Note frequency.
wxString m_units
Meter units.
wxArrayString m_noteNames
List of note names.
int m_noteNameIndex
wxTimer m_timer
Timer to update meter.
guiDeviceInfo m_deviceInfo
Device info lists.
int m_deviceInfoIndex
Index of current device.
int m_deviceSampleRateIndex
Index of sample rate for current device.
float m_pitchSample
Pitch sample.
bool m_voiced
Voiced?
guiMeter * m_meter
Meter.
bool m_runThread
Thread running flag.
wxMutex m_guiMutex
Mutex on pitch.
wxCommandEvent m_guiEvent
Event on pitch.
wxCommandEvent m_threadEvent
Event on thread error.
wxCommandEvent m_eosEvent
Event on end-of-stream.
bool m_EndOfStream
Usually end-of-file for an input stream from a file.
bool GuiTest
Run the GUI test timer and show artificial pitch estimates.
std::size_t m_guiTestTimerIntervalMs
Timer interval for the GUI test.
wxTimer m_guiTestTimer
wxWidgets timer object
wxString m_threadErrStr
Thread error message.
float m_noteRatioFromA4 [m_numNotes]
List of frequency ratio of note compared to A4.
Static Private Attributes
static const int m_numNotes = 25
Number of notes.
static const wxChar * m_noteCharStrings [m_numNotes]
List of names of notes.
static const int m_noteSemitonesFromA4 [m_numNotes]
List of semitones from A4 for each note.
static const int m_A4NoteNameIndex = 12
Index of A4.
static const float m_semitoneRatio = powf(2.0f, 1.0f/12.0f)
Frequency ratio of a semitone in 12-TET.
static const float m_1200onLog2 = 1200.0f/logf(2.0f)
Frequency ratio of a cent.
Detailed Description
A class for the PitchTuner wxWidgets GUI
Definition at line 41 of file PitchTunerFrame.h.
Constructor & Destructor Documentation
PitchTunerFrame() [1/2]
PitchTunerFrame (wxString fileName, wxString deviceName, float sampleRate, std::size_t channel, std::size_t msLatency, std::size_t subSample, float inputLpFilterCutoff, float baseLineHpFilterCutoff, bool disableHpFilter, bool disableAgc, std::size_t msWindow, std::size_t msTmax, std::size_t msTsample, float threshold, bool removeDC, float A4Frequency, wxSize frameSize, bool guiTest, bool debug)
Constructor.
Parameters
fileName Read audio waveform from this file
deviceName Read audio waveform from this device
sampleRate Sample rate
channel Audio input device channel
msLatency Audio device input buffer storage
subSample Subsample the audio waveform after lowpass filtering
inputLpFilterCutoff Low pass filter cutoff frequency
baseLineHpFilterCutoff High pass filter cutoff frequency
disableHpFilter Disable the high pass filter
disableAgc Disable the pre-processor AGC
msWindow Window width for correlation
msTmax Maximum lag time for correlation
msTsample Interval between pitch estimates
threshold Maximum threshold for the difference function
removeDC Remove DC value from correlation
A4Frequency Nominal A4 frequency
frameSize Frame size in pixels
guiTest Enable driving the GUI with fake pitch estimates
debug Enable storage of debugging information
Definition at line 87 of file PitchTunerFrame.cc.
References ID_GuiTest.
~PitchTunerFrame()
~PitchTunerFrame () throw () inline
Definition at line 84 of file PitchTunerFrame.h.
References m_meter.
PitchTunerFrame() [2/2]
PitchTunerFrame (const PitchTunerFrame &) private
Disallow copy constructor of PitchTunerFrame.
Member Function Documentation
Entry()
wxThread::ExitCode Entry () private
Pitch estimation thread entry function called by wxThreadHelper.
Definition at line 487 of file PitchTunerFrame.cc.
References guiDeviceInfo::GetDeviceName(), guiDeviceInfo::GetDeviceSampleRate(), m_baseLineHpFilterCutoff, m_channel, m_debug, m_deviceInfo, m_deviceInfoIndex, m_deviceLatencyMs, m_deviceName, m_deviceSampleRateIndex, m_disableAgc, m_disableHpFilter, m_EndOfStream, m_eosEvent, m_fileName, m_guiEvent, m_guiMutex, m_inputLpFilterCutoff, m_msTmax, m_msTsample, m_msWindow, m_pitchSample, m_removeDC, m_runThread, m_subSample, m_threadErrStr, m_threadEvent, m_threshold, m_voiced, PitchTrackerCreate(), PreProcessorCreate(), SimpleAudio::saInputStreamOpenDevice(), and SimpleAudio::saInputStreamOpenFile().
operator=()
PitchTunerFrame & operator= (const PitchTunerFrame &) private
Disallow assignment to PitchTunerFrame.
OnDeviceOptions()
void OnDeviceOptions (wxCommandEvent &) private
Device s menu item selected. Show the "Device Options" dialog box.
Definition at line 285 of file PitchTunerFrame.cc.
References guiOptionsDialog::GetA4Frequency(), guiOptionsDialog::GetDeviceNameIndex(), guiOptionsDialog::GetDeviceSampleRateIndex(), m_A4Frequency, m_A4FrequencyLower, m_A4FrequencyUpper, m_deviceInfo, m_deviceInfoIndex, m_deviceSampleRateIndex, RunThread(), and StopThread().
OnAbout()
void OnAbout (wxCommandEvent &) private
About menu item selected. Show the "about" message box.
Definition at line 315 of file PitchTunerFrame.cc.
OnQuit()
void OnQuit (wxCommandEvent &) private
Quit menu item selected.
Definition at line 359 of file PitchTunerFrame.cc.
OnPitch()
void OnPitch (wxCommandEvent &) private
A new pitch estimate is available. Update the GUI.
Definition at line 383 of file PitchTunerFrame.cc.
References m_debug, m_pitchSample, m_voiced, and UpdateGui().
OnEndOfStream()
void OnEndOfStream (wxCommandEvent &) private
End of stream event found on file or device.
Definition at line 364 of file PitchTunerFrame.cc.
OnThreadError()
void OnThreadError (wxCommandEvent &) private
Error in the pitch estimation thread.
Definition at line 369 of file PitchTunerFrame.cc.
References HandleError(), and m_threadErrStr.
OnClose()
void OnClose (wxCloseEvent &) private
Close button on frame selected.
Definition at line 374 of file PitchTunerFrame.cc.
References StopThread().
OnGuiTest()
void OnGuiTest (wxTimerEvent &) private
The GUI test waits for a timer event before updating the GUI with a fake pitch estimate
Definition at line 393 of file PitchTunerFrame.cc.
References m_debug, m_frequency, m_guiMutex, m_noteNameIndex, m_noteNames, m_pitchSample, m_voiced, and UpdateGui().
CreateGui()
void CreateGui () private
Create the wxWidgets GUI elements: meter graphic, option menu and dialog.
Definition at line 220 of file PitchTunerFrame.cc.
References HandleError(), ID_About, ID_DeviceOptions, ID_Quit, m_frequency, m_meter, m_noteNameIndex, m_noteNames, and m_units.
UpdateGui()
void UpdateGui () private
Draw the wxWidgets GUI.
Definition at line 247 of file PitchTunerFrame.cc.
References m_1200onLog2, m_A4Frequency, m_A4NoteNameIndex, m_frequency, m_guiMutex, m_meter, m_noteNameIndex, m_noteNames, m_noteRatioFromA4, m_numNotes, m_pitchSample, m_voiced, guiMeter::RePaint(), guiMeter::SetFrequency(), guiMeter::SetName(), guiMeter::SetPitch(), and guiMeter::SetPitchError().
Referenced by OnGuiTest(), and OnPitch().
FindAudioDevices()
bool FindAudioDevices () private
Interrogate the sound system and create a list of audio devices.
Definition at line 191 of file PitchTunerFrame.cc.
References guiDeviceInfo::AddDevice(), guiDeviceInfo::Alloc(), saDeviceInfo::Empty(), saDeviceInfo::getDeviceNames(), saDeviceInfo::getDeviceSampleRateList(), m_deviceInfo, and saDeviceInfo::queryInputDevices().
RunThread()
void RunThread () private
Run the pitch estimation algorithm in a separate thread.
Definition at line 440 of file PitchTunerFrame.cc.
References HandleError(), m_debug, m_guiTest, and m_runThread.
Referenced by OnDeviceOptions().
StopThread()
void StopThread () private
Stop the pitch estimation thread.
Definition at line 466 of file PitchTunerFrame.cc.
References m_debug, m_guiTest, and m_runThread.
Referenced by OnClose(), and OnDeviceOptions().
HandleError()
void HandleError (const wxString errStr) private
Show an error message string on a message box.
Definition at line 185 of file PitchTunerFrame.cc.
Referenced by CreateGui(), OnThreadError(), and RunThread().
Field Documentation
m_fileName
wxString m_fileName private
Read audio waveform from this file.
Definition at line 88 of file PitchTunerFrame.h.
Referenced by Entry().
m_deviceName
wxString m_deviceName private
Read audio waveform from this device.
Definition at line 91 of file PitchTunerFrame.h.
Referenced by Entry().
m_sampleRate
float m_sampleRate private
Audio input device sample rate.
Definition at line 94 of file PitchTunerFrame.h.
m_deviceLatencyMs
std::size_t m_deviceLatencyMs private
Audio device input buffer storage in ms.
Definition at line 97 of file PitchTunerFrame.h.
Referenced by Entry().
m_channel
std::size_t m_channel private
Audio input device channel.
Definition at line 100 of file PitchTunerFrame.h.
Referenced by Entry().
m_subSample
std::size_t m_subSample private
Subsample the audio waveform after lowpass filtering.
Definition at line 103 of file PitchTunerFrame.h.
Referenced by Entry().
m_inputLpFilterCutoff
float m_inputLpFilterCutoff private
Low pass filter cutoff frequency.
Definition at line 106 of file PitchTunerFrame.h.
Referenced by Entry().
m_baseLineHpFilterCutoff
float m_baseLineHpFilterCutoff private
High pass filter cutoff frequency.
Definition at line 109 of file PitchTunerFrame.h.
Referenced by Entry().
m_disableHpFilter
bool m_disableHpFilter private
Disable the high pass filter.
Definition at line 112 of file PitchTunerFrame.h.
Referenced by Entry().
m_disableAgc
bool m_disableAgc private
Disable the pre-processor AGC.
Definition at line 115 of file PitchTunerFrame.h.
Referenced by Entry().
m_msWindow
std::size_t m_msWindow private
Window width for correlation.
Definition at line 118 of file PitchTunerFrame.h.
Referenced by Entry().
m_msTmax
std::size_t m_msTmax private
Maximum lag time for correlation.
Definition at line 121 of file PitchTunerFrame.h.
Referenced by Entry().
m_msTsample
std::size_t m_msTsample private
Interval between pitch estimates.
Definition at line 124 of file PitchTunerFrame.h.
Referenced by Entry().
m_threshold
float m_threshold private
Maximum threshold for the difference function.
Definition at line 127 of file PitchTunerFrame.h.
Referenced by Entry().
m_removeDC
bool m_removeDC private
Remove DC value from correlation.
Definition at line 130 of file PitchTunerFrame.h.
Referenced by Entry().
m_A4Frequency
int m_A4Frequency private
Nominal A4 frequency.
Definition at line 133 of file PitchTunerFrame.h.
Referenced by OnDeviceOptions(), and UpdateGui().
m_guiTest
bool m_guiTest private
Enable GUI debugging with a fake pitch estimate.
Definition at line 136 of file PitchTunerFrame.h.
Referenced by RunThread(), and StopThread().
m_debug
bool m_debug private
Store debugging information.
Definition at line 139 of file PitchTunerFrame.h.
Referenced by Entry(), OnGuiTest(), OnPitch(), RunThread(), and StopThread().
m_deviceFound
bool m_deviceFound private
Device found.
Definition at line 142 of file PitchTunerFrame.h.
m_A4FrequencyLower
int m_A4FrequencyLower private
Meter lower valid A4 frequency.
Definition at line 145 of file PitchTunerFrame.h.
Referenced by OnDeviceOptions().
m_A4FrequencyUpper
int m_A4FrequencyUpper private
Meter upper valid A4 frequency.
Definition at line 148 of file PitchTunerFrame.h.
Referenced by OnDeviceOptions().
m_frequency
float m_frequency private
Note frequency.
Definition at line 151 of file PitchTunerFrame.h.
Referenced by CreateGui(), OnGuiTest(), and UpdateGui().
m_units
wxString m_units private
Meter units.
Definition at line 154 of file PitchTunerFrame.h.
Referenced by CreateGui().
m_noteNames
wxArrayString m_noteNames private
List of note names.
Definition at line 157 of file PitchTunerFrame.h.
Referenced by CreateGui(), OnGuiTest(), and UpdateGui().
m_noteNameIndex
int m_noteNameIndex private
Definition at line 158 of file PitchTunerFrame.h.
Referenced by CreateGui(), OnGuiTest(), and UpdateGui().
m_timer
wxTimer m_timer private
Timer to update meter.
Definition at line 161 of file PitchTunerFrame.h.
m_deviceInfo
guiDeviceInfo m_deviceInfo private
Device info lists.
Definition at line 164 of file PitchTunerFrame.h.
Referenced by Entry(), FindAudioDevices(), and OnDeviceOptions().
m_deviceInfoIndex
int m_deviceInfoIndex private
Index of current device.
Definition at line 167 of file PitchTunerFrame.h.
Referenced by Entry(), and OnDeviceOptions().
m_deviceSampleRateIndex
int m_deviceSampleRateIndex private
Index of sample rate for current device.
Definition at line 170 of file PitchTunerFrame.h.
Referenced by Entry(), and OnDeviceOptions().
m_pitchSample
float m_pitchSample private
Pitch sample.
Definition at line 173 of file PitchTunerFrame.h.
Referenced by Entry(), OnGuiTest(), OnPitch(), and UpdateGui().
m_voiced
bool m_voiced private
Voiced?
Definition at line 176 of file PitchTunerFrame.h.
Referenced by Entry(), OnGuiTest(), OnPitch(), and UpdateGui().
m_meter
guiMeter* m_meter private
Meter.
Definition at line 179 of file PitchTunerFrame.h.
Referenced by CreateGui(), UpdateGui(), and ~PitchTunerFrame().
m_runThread
bool m_runThread private
Thread running flag.
Definition at line 182 of file PitchTunerFrame.h.
Referenced by Entry(), RunThread(), and StopThread().
m_guiMutex
wxMutex m_guiMutex private
Mutex on pitch.
Definition at line 185 of file PitchTunerFrame.h.
Referenced by Entry(), OnGuiTest(), and UpdateGui().
m_guiEvent
wxCommandEvent m_guiEvent private
Event on pitch.
Definition at line 188 of file PitchTunerFrame.h.
Referenced by Entry().
m_threadEvent
wxCommandEvent m_threadEvent private
Event on thread error.
Definition at line 191 of file PitchTunerFrame.h.
Referenced by Entry().
m_eosEvent
wxCommandEvent m_eosEvent private
Event on end-of-stream.
Definition at line 194 of file PitchTunerFrame.h.
Referenced by Entry().
m_EndOfStream
bool m_EndOfStream private
Usually end-of-file for an input stream from a file.
Definition at line 197 of file PitchTunerFrame.h.
Referenced by Entry().
GuiTest
bool GuiTest private
Run the GUI test timer and show artificial pitch estimates.
Definition at line 202 of file PitchTunerFrame.h.
m_guiTestTimerIntervalMs
std::size_t m_guiTestTimerIntervalMs private
Timer interval for the GUI test.
Definition at line 205 of file PitchTunerFrame.h.
m_guiTestTimer
wxTimer m_guiTestTimer private
wxWidgets timer object
Definition at line 208 of file PitchTunerFrame.h.
m_threadErrStr
wxString m_threadErrStr private
Thread error message.
Definition at line 211 of file PitchTunerFrame.h.
Referenced by Entry(), and OnThreadError().
m_numNotes
const int m_numNotes = 25 static private
Number of notes.
Definition at line 217 of file PitchTunerFrame.h.
Referenced by UpdateGui().
m_noteCharStrings
const wxChar * m_noteCharStrings static private
Initial value:
=
  {
    wxT("A5"), wxT("G5\u266F"), wxT("G5"), wxT("F5\u266F"), wxT("F5"),
    wxT("E5"), wxT("D5\u266F"), wxT("D5"), wxT("C5\u266F"), wxT("C5"),
    wxT("B4"), wxT("A4\u266F"), wxT("A4"), wxT("G4\u266F"), wxT("G4"),
    wxT("F4\u266F"), wxT("F4"), wxT("E4"), wxT("D4\u266F"), wxT("D4"),
    wxT("C4\u266F"), wxT("C4"), wxT("B3"), wxT("A3\u266F"), wxT("A3")
  }
List of names of notes.
Definition at line 220 of file PitchTunerFrame.h.
m_noteSemitonesFromA4
const int m_noteSemitonesFromA4 static private
Initial value:
=
  {
    12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1,
    0, -1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12
  }
List of semitones from A4 for each note.
Definition at line 223 of file PitchTunerFrame.h.
m_noteRatioFromA4
float m_noteRatioFromA4[m_numNotes] private
List of frequency ratio of note compared to A4.
Definition at line 226 of file PitchTunerFrame.h.
Referenced by UpdateGui().
m_A4NoteNameIndex
const int m_A4NoteNameIndex = 12 static private
Index of A4.
Definition at line 229 of file PitchTunerFrame.h.
Referenced by UpdateGui().
m_semitoneRatio
const float m_semitoneRatio = powf(2.0f, 1.0f/12.0f) static private
Frequency ratio of a semitone in 12-TET.
Definition at line 232 of file PitchTunerFrame.h.
m_1200onLog2
const float m_1200onLog2 = 1200.0f/logf(2.0f) static private
Frequency ratio of a cent.
Definition at line 235 of file PitchTunerFrame.h.
Referenced by UpdateGui().
The documentation for this class was generated from the following files:
src/PitchTuner/PitchTunerFrame.h
src/PitchTuner/PitchTunerFrame.cc