PitchTuner: saInputStream Class Reference
saInputStream Class Reference abstract
A class for audio input streams from a file, audio device etc.
#include <saInputStream.h>
Public Member Functions
saInputStream ()
virtual ~saInputStream () throw ()
virtual std::size_t Read (std::vector< saSample > &buffer, const std::size_t framesToRead)=0
Read a buffer of frames from the saInputStream.
virtual std::size_t Read (std::vector< saSample > &buffer, const std::size_t framesToRead, const std::size_t sampleInFrame)=0
Read a buffer of samples from the saInputStream.
virtual void Clear ()=0
Clear the stream.
virtual bool OverRun ()=0
Check for stream over runs.
virtual bool EndOfSource ()=0
Check for stream end of source.
virtual std::size_t GetFramesPerSecond () const =0
Get device frame rate.
virtual std::size_t GetSamplesPerFrame () const =0
Get device samples per frame.
virtual std::size_t GetFramesPerFragment () const =0
Get device frames per fragment.
virtual std::size_t GetFramesPerStream () const =0
Get capacity of the stream.
virtual std::size_t GetFramesReadFromStream () const =0
Get frames read from the stream.
Protected Member Functions
saInputStream & operator= (const saInputStream &)
Disallow assignment to saInputStream.
saInputStream (const saInputStream &)
Disallow copy constructor of saInputStream.
Detailed Description
A class for audio input streams from a file, audio device etc.
Definition at line 15 of file saInputStream.h.
Constructor & Destructor Documentation
saInputStream() [1/2]
saInputStream () inline
Definition at line 19 of file saInputStream.h.
~saInputStream()
virtual ~saInputStream () throw () inline virtual
Definition at line 21 of file saInputStream.h.
saInputStream() [2/2]
saInputStream (const saInputStream &) protected
Disallow copy constructor of saInputStream.
Member Function Documentation
Read() [1/2]
virtual std::size_t Read (std::vector< saSample > & buffer, const std::size_t framesToRead) pure virtual
Read a buffer of frames from the saInputStream.
Parameters
buffer vector< saSample >
framesToRead
Returns
number of frames read
Implemented in saInputStreamImpl.
Referenced by PreProcessorImpl::Read().
Read() [2/2]
virtual std::size_t Read (std::vector< saSample > & buffer, const std::size_t framesToRead, const std::size_t sampleInFrame) pure virtual
Read a buffer of samples from the saInputStream.
Parameters
buffer vector of saSample
framesToRead frames to read
sampleInFrame read sample in frame
Returns
number of frames read
Implemented in saInputStreamImpl.
Clear()
virtual void Clear () pure virtual
Clear the stream.
Implemented in saInputStreamImpl.
Referenced by PreProcessorImpl::Read().
OverRun()
virtual bool OverRun () pure virtual
Check for stream over runs.
Returns
over run occurred
Implemented in saInputStreamImpl.
Referenced by PreProcessorImpl::Read().
EndOfSource()
virtual bool EndOfSource () pure virtual
Check for stream end of source.
Returns
end of source occurred
Implemented in saInputStreamImpl.
Referenced by PreProcessorImpl::Read().
GetFramesPerSecond()
virtual std::size_t GetFramesPerSecond () const pure virtual
Get device frame rate.
Returns
frames per second
Implemented in saInputStreamImpl.
GetSamplesPerFrame()
virtual std::size_t GetSamplesPerFrame () const pure virtual
Get device samples per frame.
Returns
samples per frame
Implemented in saInputStreamImpl.
GetFramesPerFragment()
virtual std::size_t GetFramesPerFragment () const pure virtual
Get device frames per fragment.
Returns
frames per fragment
Implemented in saInputStreamImpl.
GetFramesPerStream()
virtual std::size_t GetFramesPerStream () const pure virtual
Get capacity of the stream.
Returns
frames per stream
Implemented in saInputStreamImpl.
GetFramesReadFromStream()
virtual std::size_t GetFramesReadFromStream () const pure virtual
Get frames read from the stream.
Returns
frames read from stream
Implemented in saInputStreamImpl.
operator=()
saInputStream & operator= (const saInputStream &) protected
Disallow assignment to saInputStream.
The documentation for this class was generated from the following file:
src/SimpleAudio/saInputStream.h