PitchTuner: guiOptionsDialog Class Reference
guiOptionsDialog Class Reference
A class for the wxWidgets GUI options dialog.
#include <guiOptionsDialog.h>
Public Member Functions
guiOptionsDialog (wxFrame *parent, const wxString &caption, const guiDeviceInfo &deviceInfo, const int deviceNameIndex, const int deviceSampleRateIndex, const int A4FrequencyLower, const int A4FrequencyUpper, const int A4Frequency)
Constructor.
~guiOptionsDialog ()
int GetDeviceNameIndex ()
Get selected device name index.
int GetDeviceSampleRateIndex ()
Get selected device sample rate index.
int GetA4Frequency ()
Get selected A4 frequency index.
Private Member Functions
void OnOk (wxCommandEvent &)
void OnCancel (wxCommandEvent &)
guiOptionsDialog (const guiOptionsDialog &)
guiOptionsDialog & operator= (const guiOptionsDialog &)
Private Attributes
wxChoice * m_deviceNameCtrl
Choose device name.
wxChoice * m_sampleRateCtrl
Choose sample rate.
wxSpinCtrl * m_A4FrequencyCtrl
Choose A4 frequency.
int m_deviceNameIndex
int m_sampleRateIndex
int m_A4Frequency
Detailed Description
A class for the wxWidgets GUI options dialog.
Definition at line 20 of file guiOptionsDialog.h.
Constructor & Destructor Documentation
guiOptionsDialog() [1/2]
guiOptionsDialog (wxFrame * parent, const wxString & caption, const guiDeviceInfo & deviceInfo, const int deviceNameIndex, const int deviceSampleRateIndex, const int A4FrequencyLower, const int A4FrequencyUpper, const int A4Frequency)
Constructor.
Parameters
parent parent frame
caption caption
deviceInfo list of devices
deviceNameIndex initial device name index
deviceSampleRateIndex initial device sample rate index
A4FrequencyLower lower A4 frequency
A4FrequencyUpper upper A4 frequency
A4Frequency initial A4 frequency
Definition at line 13 of file guiOptionsDialog.cc.
References guiOptionsDialog::OnCancel(), and guiOptionsDialog::OnOk().
~guiOptionsDialog()
~guiOptionsDialog ()
Definition at line 129 of file guiOptionsDialog.cc.
guiOptionsDialog() [2/2]
guiOptionsDialog (const guiOptionsDialog &) private
Member Function Documentation
GetDeviceNameIndex()
int GetDeviceNameIndex () inline
Get selected device name index.
Returns
device name index
Definition at line 45 of file guiOptionsDialog.h.
References guiOptionsDialog::m_deviceNameIndex.
Referenced by PitchTunerFrame::OnDeviceOptions().
GetDeviceSampleRateIndex()
int GetDeviceSampleRateIndex () inline
Get selected device sample rate index.
Returns
device sample rate index
Definition at line 49 of file guiOptionsDialog.h.
References guiOptionsDialog::m_sampleRateIndex.
Referenced by PitchTunerFrame::OnDeviceOptions().
GetA4Frequency()
int GetA4Frequency () inline
Get selected A4 frequency index.
Returns
A4 frequency index
Definition at line 53 of file guiOptionsDialog.h.
References guiOptionsDialog::m_A4Frequency.
Referenced by PitchTunerFrame::OnDeviceOptions().
OnOk()
void OnOk (wxCommandEvent &) private
Definition at line 134 of file guiOptionsDialog.cc.
References guiOptionsDialog::m_A4Frequency, guiOptionsDialog::m_A4FrequencyCtrl, guiOptionsDialog::m_deviceNameCtrl, guiOptionsDialog::m_deviceNameIndex, guiOptionsDialog::m_sampleRateCtrl, and guiOptionsDialog::m_sampleRateIndex.
Referenced by guiOptionsDialog::guiOptionsDialog().
OnCancel()
void OnCancel (wxCommandEvent &) private
Definition at line 143 of file guiOptionsDialog.cc.
Referenced by guiOptionsDialog::guiOptionsDialog().
operator=()
guiOptionsDialog & operator= (const guiOptionsDialog &) private
Field Documentation
m_deviceNameCtrl
wxChoice* m_deviceNameCtrl private
Choose device name.
Definition at line 58 of file guiOptionsDialog.h.
Referenced by guiOptionsDialog::OnOk().
m_sampleRateCtrl
wxChoice* m_sampleRateCtrl private
Choose sample rate.
Definition at line 61 of file guiOptionsDialog.h.
Referenced by guiOptionsDialog::OnOk().
m_A4FrequencyCtrl
wxSpinCtrl* m_A4FrequencyCtrl private
Choose A4 frequency.
Definition at line 64 of file guiOptionsDialog.h.
Referenced by guiOptionsDialog::OnOk().
m_deviceNameIndex
int m_deviceNameIndex private
Definition at line 67 of file guiOptionsDialog.h.
Referenced by guiOptionsDialog::GetDeviceNameIndex(), and guiOptionsDialog::OnOk().
m_sampleRateIndex
int m_sampleRateIndex private
Definition at line 68 of file guiOptionsDialog.h.
Referenced by guiOptionsDialog::GetDeviceSampleRateIndex(), and guiOptionsDialog::OnOk().
m_A4Frequency
int m_A4Frequency private
Definition at line 69 of file guiOptionsDialog.h.
Referenced by guiOptionsDialog::GetA4Frequency(), and guiOptionsDialog::OnOk().
The documentation for this class was generated from the following files:
src/PitchTuner/guiOptionsDialog.h
src/PitchTuner/guiOptionsDialog.cc