PitchTuner: saDeviceInfo Class Reference
saDeviceInfo Class Reference
A class for obtaining information about an audio device.
#include <saDeviceInfo.h>
Data Structures
struct showListEntry
Public Member Functions
saDeviceInfo ()
~saDeviceInfo ()
void queryInputDevices ()
Query simple audio input device info.
void getDeviceNames (saDeviceInfoDeviceNameList &deviceNameList)
Get device names.
void getDeviceSampleRateList (saDeviceInfoDeviceName &deviceName, saDeviceInfoSampleRateList &sampleRateList)
Get device sample rates.
bool Empty ()
Device info list empty?
void showDevices ()
Show device info.
Private Types
typedef std::pair< saDeviceInfoDeviceName, saDeviceInfoSampleRateList > saDeviceInfoListEntry
typedef std::vector< saDeviceInfoListEntry > saDeviceInfoList
Private Member Functions
saDeviceInfo & operator= (const saDeviceInfo &)
Disallow assignment to saDeviceInfo.
saDeviceInfo (const saDeviceInfo &)
Disallow copy constructor of saDeviceInfo.
Private Attributes
saDeviceInfoList deviceInfoList
Internal list of available devices.
Detailed Description
A class for obtaining information about an audio device.
Definition at line 37 of file saDeviceInfo.h.
Member Typedef Documentation
saDeviceInfoListEntry
saDeviceInfoListEntry private
Pair of device name and vector of sample rates
Definition at line 77 of file saDeviceInfo.h.
saDeviceInfoList
saDeviceInfoList private
List (vector) of pairs of device name and vector of sample rates
Definition at line 81 of file saDeviceInfo.h.
Constructor & Destructor Documentation
saDeviceInfo() [1/2]
saDeviceInfo () inline
Definition at line 41 of file saDeviceInfo.h.
~saDeviceInfo()
~saDeviceInfo () inline
Definition at line 43 of file saDeviceInfo.h.
saDeviceInfo() [2/2]
saDeviceInfo (const saDeviceInfo &) private
Disallow copy constructor of saDeviceInfo.
Member Function Documentation
queryInputDevices()
void queryInputDevices ()
Query simple audio input device info.
Definition at line 27 of file saDeviceInfoDetail.cc.
References saDeviceInfo::deviceInfoList.
Referenced by PitchTunerFrame::FindAudioDevices().
getDeviceNames()
void getDeviceNames (saDeviceInfoDeviceNameList & deviceNameList)
Get device names.
Parameters
deviceNameList reference to a vector of device names
Definition at line 16 of file saDeviceInfo.cc.
References saDeviceInfo::deviceInfoList.
Referenced by PitchTunerFrame::FindAudioDevices().
getDeviceSampleRateList()
void getDeviceSampleRateList (saDeviceInfoDeviceName & deviceName, saDeviceInfoSampleRateList & sampleRateList)
Get device sample rates.
Parameters
deviceName
sampleRateList reference to a vector of sample rates
Definition at line 28 of file saDeviceInfo.cc.
References saDeviceInfo::deviceInfoList.
Referenced by PitchTunerFrame::FindAudioDevices().
Empty()
bool Empty ()
Device info list empty?
Returns
Device list is empty
Definition at line 65 of file saDeviceInfo.cc.
References saDeviceInfo::deviceInfoList.
Referenced by PitchTunerFrame::FindAudioDevices().
showDevices()
void showDevices ()
Show device info.
Definition at line 71 of file saDeviceInfo.cc.
References saDeviceInfo::deviceInfoList.
operator=()
saDeviceInfo & operator= (const saDeviceInfo &) private
Disallow assignment to saDeviceInfo.
Field Documentation
deviceInfoList
saDeviceInfoList deviceInfoList private
Internal list of available devices.
Definition at line 84 of file saDeviceInfo.h.
Referenced by saDeviceInfo::Empty(), saDeviceInfo::getDeviceNames(), saDeviceInfo::getDeviceSampleRateList(), saDeviceInfo::queryInputDevices(), and saDeviceInfo::showDevices().
The documentation for this class was generated from the following files:
src/SimpleAudio/saDeviceInfo.h
src/SimpleAudio/saDeviceInfo.cc
src/SimpleAudio/alsa/saDeviceInfoDetail.cc