PitchTuner: SimpleAudio Namespace Reference
SimpleAudio Namespace Reference
Data Structures
class saCircBuffOverRun
Exception classes for the circular buffer.
class saCircBuffUnderRun
class saCircBuffCantCopy
class saCircBuffDefaultConverter
class saCircBuffCopyByteWise
class saCircBuffCopyImplicit
class saCircBuffCopyExplicit
class saCircBuff
SimpleAudio circular buffer class.
class saDeviceInfo
A class for obtaining information about an audio device.
struct ReadFromFile
class saInputFileAscii
class saInputFileSelector
class saInputFileWav
class saInputSource
A class for audio input devices.
struct DecimateSource
class saInputStreamImpl
class saInputStream
A class for audio input streams from a file, audio device etc.
class saOutputFileSelector
class saOutputFileWav
class saOutputSink
A class for audio output devices.
class saOutputStreamImpl
struct saOutputStream
A class for audio output streams to a file, audio device etc.
struct saSampleTo
struct saSampleFromSource
struct saSampleFromSource< saDeviceType >
struct saSampleToSink
struct saSampleToSink< saDeviceType >
class saSampleBase
A class for audio samples.
struct saSampleTestTo
A conversion functor.
struct saWavHeader
struct saSwapSample
struct saSwapSample< int16_t >
struct saSwapSample< uint16_t >
struct saSwapSample< int32_t >
struct saSwapSample< uint32_t >
class saInputDevice
class saOutputDevice
Typedefs
typedef std::string saDeviceInfoDeviceName
typedef std::vector< saDeviceInfoDeviceName > saDeviceInfoDeviceNameList
typedef std::size_t saSampleRate
typedef std::vector< saSampleRate > saDeviceInfoSampleRateList
typedef int16_t saDeviceType
typedef saInputSource *(* saInputSourceOpenFileCallBack) (const std::string &name)
typedef SingletonHolder::SingletonHolder< saInputFileSelector< ThreadingModel::SingleThreaded, MutexPolicy::NoMutex >, CreationPolicy::CreateUsingNew, LifetimePolicy::DefaultLifetime, ThreadingModel::SingleThreaded, MutexPolicy::NoMutex > saSingletonInputFileSelector
typedef saOutputSink *(* saOutputSinkOpenFileCallBack) (const std::string &name, const std::size_t sampleRate, const std::size_t channels)
typedef SingletonHolder::SingletonHolder< saOutputFileSelector< ThreadingModel::SingleThreaded, MutexPolicy::NoMutex >, CreationPolicy::CreateUsingNew, LifetimePolicy::DefaultLifetime, ThreadingModel::SingleThreaded, MutexPolicy::NoMutex > saSingletonOutputFileSelector
typedef saSampleBase< float, double, true, false, false > saSample
typedef saSampleBase< int32_t, int64_t, true, true, true > saSampleTest
Define saSampleTest.
typedef struct SimpleAudio::saWavHeader saWavHeader
Functions
saInputSource * saInputSourceOpenFileAscii (const std::string &fileName)
saInputSource * saInputSourceOpenFile (const std::string &fileName)
saInputSource * saInputSourceOpenFileWav (const std::string &fileName)
Open input WAV file.
saInputSource * saInputSourceOpenDevice (const std::string &deviceName, const std::size_t framesPerSecond, const std::size_t msLatency, const std::size_t channels=1, const bool debug=false)
saInputStream * saInputStreamOpenDevice (const std::string &deviceName, const std::size_t framesPerSecond, const std::size_t msDeviceLatency, const std::size_t channels=1, const bool debug=false)
Open a simple audio input stream from a device.
saInputStream * saInputStreamOpenFile (const std::string &fileName)
Open a simple audio input stream from a file.
saOutputSink * saOutputSinkOpenFile (const std::string &fileName, const std::size_t framesPerSecond, const std::size_t channels=1)
Open a file sink.
saOutputSink * saOutputSinkOpenFileWav (const std::string &fileName, const std::size_t frameRate, const std::size_t channels=1)
Open output WAV file.
saOutputSink * saOutputSinkOpenDevice (const std::string &deviceName, const std::size_t framesPerSecond, const std::size_t msLatency, const std::size_t channels=1)
Open a device sink.
saOutputStream * saOutputStreamOpenDevice (const std::string &deviceName, const std::size_t framesPerSecond, const std::size_t msDeviceLatency, const std::size_t channels=1)
Open a simple audio output stream to a device.
saOutputStream * saOutputStreamOpenFile (const std::string &fileName, const std::size_t framesPerSecond, const std::size_t channels=1)
Open a simple audio output stream to a file.
template<>
std::ostream & operator<< (std::ostream &os, const saSample &rhs)
Implementation of <<.
template<typename T, typename L, bool S, bool O, bool U>
std::ostream & operator<< (std::ostream &, const saSampleBase< T, L, S, O, U > &)
Forward declaration of << for saSampleBase.
template<typename T, typename L, bool S, bool O, bool U>
saSampleBase< T, L, S, O, U > operator+ (const saSampleBase< T, L, S, O, U > &lhs, const saSampleBase< T, L, S, O, U > &rhs)
template<typename T, typename L, bool S, bool O, bool U, typename Trhs>
saSampleBase< T, L, S, O, U > operator+ (const saSampleBase< T, L, S, O, U > &lhs, const Trhs &rhs)
template<typename T, typename L, bool S, bool O, bool U, typename Tlhs>
saSampleBase< T, L, S, O, U > operator+ (const Tlhs &lhs, const saSampleBase< T, L, S, O, U > &rhs)
template<typename T, typename L, bool S, bool O, bool U>
saSampleBase< T, L, S, O, U > operator- (const saSampleBase< T, L, S, O, U > &lhs, const saSampleBase< T, L, S, O, U > &rhs)
template<typename T, typename L, bool S, bool O, bool U, typename Trhs>
saSampleBase< T, L, S, O, U > operator- (const saSampleBase< T, L, S, O, U > &lhs, const Trhs &rhs)
template<typename T, typename L, bool S, bool O, bool U, typename Tlhs>
saSampleBase< T, L, S, O, U > operator- (const Tlhs &lhs, const saSampleBase< T, L, S, O, U > &rhs)
template<typename T, typename L, bool S, bool O, bool U>
saSampleBase< T, L, S, O, U > operator* (const saSampleBase< T, L, S, O, U > &lhs, const saSampleBase< T, L, S, O, U > &rhs)
template<typename T, typename L, bool S, bool O, bool U, typename Trhs>
saSampleBase< T, L, S, O, U > operator* (const saSampleBase< T, L, S, O, U > &lhs, const Trhs &rhs)
template<typename T, typename L, bool S, bool O, bool U, typename Tlhs>
saSampleBase< T, L, S, O, U > operator* (const Tlhs &lhs, const saSampleBase< T, L, S, O, U > &rhs)
template<typename T, typename L, bool S, bool O, bool U>
saSampleBase< T, L, S, O, U > operator/ (const saSampleBase< T, L, S, O, U > &lhs, const saSampleBase< T, L, S, O, U > &rhs)
template<typename T, typename L, bool S, bool O, bool U, typename Trhs>
saSampleBase< T, L, S, O, U > operator/ (const saSampleBase< T, L, S, O, U > &lhs, const Trhs &rhs)
template<typename T, typename L, bool S, bool O, bool U, typename Tlhs>
saSampleBase< T, L, S, O, U > operator/ (const Tlhs &lhs, const saSampleBase< T, L, S, O, U > &rhs)
template<>
std::ostream & operator<< (std::ostream &os, const saSampleTest &rhs)
Implementation of <<.
void saSwap2Bytes (char *buf)
void saSwap4Bytes (char *buf)
void saSwapShort (uint16_t &buffer)
void saSwapShort (int16_t &buffer)
void saSwapShort (int16_t *buffer, std::size_t shorts)
void saSwapLong (int32_t &buffer)
void saSwapLong (uint32_t &buffer)
bool saIsLittleEndian ()
bool saCompareID (char ID[4], std::string Str)
void saSwapWavHeader (saWavHeader *wavHeader)
static std::size_t saInputDeviceRead (snd_pcm_t *handle, saInputSource::saSourceType *buffer, const std::size_t framesToRead, bool &isOverRun)
static void saOutputDeviceWrite (snd_pcm_t *handle, saOutputSink::saSinkType *buffer, const std::size_t framesToWrite, bool &isUnderRun)
Typedef Documentation
saDeviceInfoDeviceName
typedef std::string saDeviceInfoDeviceName
Device name
Definition at line 21 of file saDeviceInfo.h.
saDeviceInfoDeviceNameList
typedef std::vector< saDeviceInfoDeviceName > saDeviceInfoDeviceNameList
List (vector for random access) of device names
Definition at line 25 of file saDeviceInfo.h.
saSampleRate
typedef std::size_t saSampleRate
Type of sample rate
List (vector for random access) of sample rates
Definition at line 29 of file saDeviceInfo.h.
saDeviceInfoSampleRateList
typedef std::vector< saSampleRate > saDeviceInfoSampleRateList
Definition at line 33 of file saDeviceInfo.h.
saDeviceType
typedef int16_t saDeviceType
The audio device waveform data type
Definition at line 13 of file saDeviceType.h.
saInputSourceOpenFileCallBack
typedef saInputSource *(* saInputSourceOpenFileCallBack) (const std::string &name)
Definition at line 14 of file saInputFileSelector.h.
saSingletonInputFileSelector
typedef SingletonHolder::SingletonHolder< saInputFileSelector<ThreadingModel::SingleThreaded, MutexPolicy::NoMutex>, CreationPolicy::CreateUsingNew, LifetimePolicy::DefaultLifetime, ThreadingModel::SingleThreaded, MutexPolicy::NoMutex > saSingletonInputFileSelector
Definition at line 39 of file saInputFileSelector.h.
saOutputSinkOpenFileCallBack
typedef saOutputSink *(* saOutputSinkOpenFileCallBack) (const std::string &name, const std::size_t sampleRate, const std::size_t channels)
Definition at line 14 of file saOutputFileSelector.h.
saSingletonOutputFileSelector
typedef SingletonHolder::SingletonHolder< saOutputFileSelector<ThreadingModel::SingleThreaded, MutexPolicy::NoMutex>, CreationPolicy::CreateUsingNew, LifetimePolicy::DefaultLifetime, ThreadingModel::SingleThreaded, MutexPolicy::NoMutex > saSingletonOutputFileSelector
Definition at line 44 of file saOutputFileSelector.h.
saSample
typedef saSampleBase<float, double, true, false, false> saSample
The usual saSample, derived from saSampleBase
Definition at line 17 of file saSample.h.
saSampleTest
typedef saSampleBase< int32_t, int64_t, true, true, true > saSampleTest
Define saSampleTest.
Definition at line 14 of file saSampleTest.h.
saWavHeader
typedef struct SimpleAudio::saWavHeader saWavHeader
Function Documentation
saInputSourceOpenFileAscii()
saInputSource * saInputSourceOpenFileAscii (const std::string & fileName)
Definition at line 231 of file saInputFileAscii.cc.
Referenced by main().
saInputSourceOpenFile()
saInputSource * saInputSourceOpenFile (const std::string & fileName)
Definition at line 55 of file saInputFileSelector.cc.
Referenced by saInputStreamOpenFile().
saInputSourceOpenFileWav()
saInputSource * saInputSourceOpenFileWav (const std::string & fileName)
Open input WAV file.
Parameters
fileName file name
Returns
A pointer to an saInputSource to read from
Definition at line 175 of file saInputFileWav.cc.
References saWavHeader::DataChunkID, saWavHeader::DataChunkSize, saWavHeader::FormatBitsPerSample, saWavHeader::FormatChannels, saWavHeader::FormatChunkID, saWavHeader::FormatTag, saWavHeader::RiffChunkID, saWavHeader::RiffFormat, saCompareID(), saIsLittleEndian(), and saSwapWavHeader().
Referenced by main(), main(), and PitchTuner::OnInit().
saInputSourceOpenDevice()
saInputSource * saInputSourceOpenDevice (const std::string & deviceName, const std::size_t framesPerSecond, const std::size_t msLatency, const std::size_t channels = 1, const bool debug = false)
saInputSourceOpenDevice
Parameters
deviceName Name of audio input device to open
framesPerSecond Sample rate to set in the audio device
msLatency Size of buffer of the device data in milliseconds
channels Channels per frame of the device
debug Enable debugging output
Returns
A pointer to an saInputSource
Definition at line 318 of file saInputDevice.cc.
Referenced by saInputStreamOpenDevice().
saInputStreamOpenDevice()
saInputStream * saInputStreamOpenDevice (const std::string & deviceName, const std::size_t framesPerSecond, const std::size_t msDeviceLatency, const std::size_t channels = 1, const bool debug = false)
Open a simple audio input stream from a device.
Parameters
deviceName device name
framesPerSecond sample rate
msDeviceLatency device fragment buffer size (stream latency in ms)
channels number of channels on device
debug
Returns
pointer to saInputStream
Definition at line 358 of file saInputStream.cc.
References saInputSourceOpenDevice().
Referenced by PitchTunerFrame::Entry(), and main().
saInputStreamOpenFile()
saInputStream * saInputStreamOpenFile (const std::string & fileName)
Open a simple audio input stream from a file.
Parameters
fileName file name
Returns
pointer to saInputStream
Definition at line 372 of file saInputStream.cc.
References saInputSourceOpenFile().
Referenced by PitchTunerFrame::Entry(), and main().
saOutputSinkOpenFile()
saOutputSink * saOutputSinkOpenFile (const std::string & fileName, const std::size_t framesPerSecond, const std::size_t channels = 1)
Open a file sink.
Parameters
fileName name of file
framesPerSecond frame rate
channels samples per frame
Returns
pointer to saOutputSink
Definition at line 57 of file saOutputFileSelector.cc.
Referenced by saOutputStreamOpenFile().
saOutputSinkOpenFileWav()
saOutputSink * saOutputSinkOpenFileWav (const std::string & fileName, const std::size_t frameRate, const std::size_t channels = 1)
Open output WAV file.
Parameters
fileName file name
frameRate frame rate (sample rate)
channels channels (samples) per frame
Returns
A pointer to an output WAV file to write to
Definition at line 237 of file saOutputFileWav.cc.
Referenced by main(), and main().
saOutputSinkOpenDevice()
saOutputSink * saOutputSinkOpenDevice (const std::string & deviceName, const std::size_t framesPerSecond, const std::size_t msLatency, const std::size_t channels = 1)
Open a device sink.
Parameters
deviceName name of device
framesPerSecond frame rate
msLatency device storage latency in milliseconds
channels samples per frame
Returns
pointer to saOutputSink
Definition at line 311 of file saOutputDevice.cc.
Referenced by saOutputStreamOpenDevice().
saOutputStreamOpenDevice()
saOutputStream * saOutputStreamOpenDevice (const std::string & deviceName, const std::size_t framesPerSecond, const std::size_t msDeviceLatency, const std::size_t channels = 1)
Open a simple audio output stream to a device.
Parameters
deviceName name of device
framesPerSecond sample rate
msDeviceLatency device fragment buffer size (stream latency in ms)
channels channels (samples) per fragment
Returns
pointer to saOutputStream
Definition at line 200 of file saOutputStream.cc.
References saOutputSinkOpenDevice().
Referenced by main().
saOutputStreamOpenFile()
saOutputStream * saOutputStreamOpenFile (const std::string & fileName, const std::size_t framesPerSecond, const std::size_t channels = 1)
Open a simple audio output stream to a file.
Parameters
fileName name of file
framesPerSecond frame (sample) rate
channels samples per frame
Returns
pointer saOutputStream
Definition at line 213 of file saOutputStream.cc.
References saOutputSinkOpenFile().
Referenced by main().
operator<<() [1/3]
template<> std::ostream & operator<< (std::ostream & os, const saSample & rhs)
Implementation of <<.
Definition at line 11 of file saSample.cc.
References saSampleBase< T, L, S, O, U >::to().
operator<<() [2/3]
template<typename T, typename L, bool S, bool O, bool U> std::ostream & operator<< (std::ostream & , const saSampleBase< T, L, S, O, U > &)
Forward declaration of << for saSampleBase.
operator+() [1/3]
template<typename T, typename L, bool S, bool O, bool U> saSampleBase< T, L, S, O, U > operator+ (const saSampleBase< T, L, S, O, U > & lhs, const saSampleBase< T, L, S, O, U > & rhs)
Definition at line 564 of file saSampleBase.h.
operator+() [2/3]
template<typename T, typename L, bool S, bool O, bool U, typename Trhs> saSampleBase< T, L, S, O, U > operator+ (const saSampleBase< T, L, S, O, U > & lhs, const Trhs & rhs)
Definition at line 573 of file saSampleBase.h.
operator+() [3/3]
template<typename T, typename L, bool S, bool O, bool U, typename Tlhs> saSampleBase< T, L, S, O, U > operator+ (const Tlhs & lhs, const saSampleBase< T, L, S, O, U > & rhs)
Definition at line 582 of file saSampleBase.h.
operator-() [1/3]
template<typename T, typename L, bool S, bool O, bool U> saSampleBase< T, L, S, O, U > operator- (const saSampleBase< T, L, S, O, U > & lhs, const saSampleBase< T, L, S, O, U > & rhs)
Definition at line 591 of file saSampleBase.h.
operator-() [2/3]
template<typename T, typename L, bool S, bool O, bool U, typename Trhs> saSampleBase< T, L, S, O, U > operator- (const saSampleBase< T, L, S, O, U > & lhs, const Trhs & rhs)
Definition at line 600 of file saSampleBase.h.
operator-() [3/3]
template<typename T, typename L, bool S, bool O, bool U, typename Tlhs> saSampleBase< T, L, S, O, U > operator- (const Tlhs & lhs, const saSampleBase< T, L, S, O, U > & rhs)
Definition at line 609 of file saSampleBase.h.
operator*() [1/3]
template<typename T, typename L, bool S, bool O, bool U> saSampleBase< T, L, S, O, U > operator* (const saSampleBase< T, L, S, O, U > & lhs, const saSampleBase< T, L, S, O, U > & rhs)
Definition at line 618 of file saSampleBase.h.
operator*() [2/3]
template<typename T, typename L, bool S, bool O, bool U, typename Trhs> saSampleBase< T, L, S, O, U > operator* (const saSampleBase< T, L, S, O, U > & lhs, const Trhs & rhs)
Definition at line 627 of file saSampleBase.h.
operator*() [3/3]
template<typename T, typename L, bool S, bool O, bool U, typename Tlhs> saSampleBase< T, L, S, O, U > operator* (const Tlhs & lhs, const saSampleBase< T, L, S, O, U > & rhs)
Definition at line 636 of file saSampleBase.h.
operator/() [1/3]
template<typename T, typename L, bool S, bool O, bool U> saSampleBase< T, L, S, O, U > operator/ (const saSampleBase< T, L, S, O, U > & lhs, const saSampleBase< T, L, S, O, U > & rhs)
Definition at line 645 of file saSampleBase.h.
operator/() [2/3]
template<typename T, typename L, bool S, bool O, bool U, typename Trhs> saSampleBase< T, L, S, O, U > operator/ (const saSampleBase< T, L, S, O, U > & lhs, const Trhs & rhs)
Definition at line 654 of file saSampleBase.h.
operator/() [3/3]
template<typename T, typename L, bool S, bool O, bool U, typename Tlhs> saSampleBase< T, L, S, O, U > operator/ (const Tlhs & lhs, const saSampleBase< T, L, S, O, U > & rhs)
Definition at line 663 of file saSampleBase.h.
operator<<() [3/3]
template<> std::ostream & operator<< (std::ostream & os, const saSampleTest & rhs)
Implementation of <<.
Definition at line 12 of file saSampleTest.cc.
References saSampleBase< T, L, S, O, U >::to().
saSwap2Bytes()
void saSwap2Bytes (char * buf)
Definition at line 11 of file saWavHeader.cc.
Referenced by saSwapSample< int16_t >::operator()(), saSwapSample< uint16_t >::operator()(), saSwapShort(), and saSwapShort().
saSwap4Bytes()
void saSwap4Bytes (char * buf)
Definition at line 18 of file saWavHeader.cc.
Referenced by saSwapSample< int32_t >::operator()(), saSwapSample< uint32_t >::operator()(), saSwapLong(), and saSwapLong().
saSwapShort() [1/3]
void saSwapShort (uint16_t & buffer)
Definition at line 25 of file saWavHeader.cc.
References saSwap2Bytes().
Referenced by saSwapShort(), and saSwapWavHeader().
saSwapShort() [2/3]
void saSwapShort (int16_t & buffer)
Definition at line 30 of file saWavHeader.cc.
References saSwap2Bytes().
saSwapShort() [3/3]
void saSwapShort (int16_t * buffer, std::size_t shorts)
Definition at line 35 of file saWavHeader.cc.
References saSwapShort().
saSwapLong() [1/2]
void saSwapLong (int32_t & buffer)
Definition at line 43 of file saWavHeader.cc.
References saSwap4Bytes().
Referenced by saSwapWavHeader().
saSwapLong() [2/2]
void saSwapLong (uint32_t & buffer)
Definition at line 48 of file saWavHeader.cc.
References saSwap4Bytes().
saIsLittleEndian()
bool saIsLittleEndian ()
Definition at line 54 of file saWavHeader.cc.
Referenced by saInputFileWav::Collect(), saOutputFileWav::Dispatch(), saInputSourceOpenFileWav(), and saOutputFileWav::WriteWavFileHeader().
saCompareID()
bool saCompareID (char ID[4], std::string Str)
Definition at line 60 of file saWavHeader.cc.
Referenced by saInputSourceOpenFileWav().
saSwapWavHeader()
void saSwapWavHeader (saWavHeader * wavHeader)
Definition at line 67 of file saWavHeader.cc.
References saWavHeader::DataChunkSize, saWavHeader::FormatAvgBytesPerSec, saWavHeader::FormatBitsPerSample, saWavHeader::FormatBlockAlign, saWavHeader::FormatChannels, saWavHeader::FormatChunkSize, saWavHeader::FormatSamplesPerSec, saWavHeader::FormatTag, saWavHeader::RiffChunkSize, saSwapLong(), and saSwapShort().
Referenced by saInputSourceOpenFileWav(), and saOutputFileWav::WriteWavFileHeader().
saInputDeviceRead()
std::size_t saInputDeviceRead (snd_pcm_t * handle, saInputSource::saSourceType * buffer, const std::size_t framesToRead, bool & isOverRun) static
Definition at line 268 of file saInputDevice.cc.
Referenced by saInputDevice::Collect().
saOutputDeviceWrite()
void saOutputDeviceWrite (snd_pcm_t * handle, saOutputSink::saSinkType * buffer, const std::size_t framesToWrite, bool & isUnderRun) static
Definition at line 262 of file saOutputDevice.cc.
Referenced by saOutputDevice::Dispatch().