PitchTuner: src/PitchTracker/PitchTracker_test.cc File Reference
PitchTracker_test.cc File Reference
#include <iostream>
#include <sstream>
#include <vector>
#include <deque>
#include <algorithm>
#include <iomanip>
#include <memory>
#include <list>
#include <iterator>
#include "saSample.h"
#include "saInputSource.h"
#include "saInputFileWav.h"
#include "saInputStream.h"
#include "PreProcessor.h"
#include "PitchTracker.h"
Functions
void Usage ()
void ParseOptions (int argc, char *argv[], bool &helpReq, bool &debugReq, std::size_t &maxPitchSamples, std::size_t &channel, std::size_t &sampleRate, std::size_t &msDeviceLatency, std::size_t &msWindow, std::size_t &msTmax, std::size_t &msTsample, std::size_t &subSample, float &inputLpFilterCutoff, float &baseLineHpFilterCutoff, bool &disableHpFilter, bool &disableAgc, float &threshold, bool &removeDC, std::string &sourceName, bool &fileReq, bool &maxPitchSamplesSet)
int main (int argc, char *argv[])
Function Documentation
Usage()
void Usage ()
Definition at line 42 of file PitchTracker_test.cc.
Referenced by ParseOptions().
ParseOptions()
void ParseOptions (int argc, char * argv[], bool & helpReq, bool & debugReq, std::size_t & maxPitchSamples, std::size_t & channel, std::size_t & sampleRate, std::size_t & msDeviceLatency, std::size_t & msWindow, std::size_t & msTmax, std::size_t & msTsample, std::size_t & subSample, float & inputLpFilterCutoff, float & baseLineHpFilterCutoff, bool & disableHpFilter, bool & disableAgc, float & threshold, bool & removeDC, std::string & sourceName, bool & fileReq, bool & maxPitchSamplesSet)
Definition at line 85 of file PitchTracker_test.cc.
References Usage().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 245 of file PitchTracker_test.cc.
References ParseOptions(), PitchTrackerCreate(), PreProcessorCreate(), SimpleAudio::saInputSourceOpenFileWav(), SimpleAudio::saInputStreamOpenDevice(), and SimpleAudio::saInputStreamOpenFile().