PitchTuner: src/SimpleAudio/saCircBuff_test.cc File Reference
saCircBuff_test.cc File Reference
#include <chrono>
#include <iostream>
#include <iomanip>
#include <memory>
#include <thread>
#include <semaphore>
#include <stdexcept>
#include <cstdint>
#include <cstring>
#include "saSample.h"
#include "saCircBuff.h"
Typedefs
using binary_semaphore = std::counting_semaphore< 1 >
typedef saCircBuff< int16_t, int16_t, int16_t, saCircBuffCopyByteWise< int16_t >, saCircBuffCopyByteWise< int16_t >, true, true > saCircBuff_16_16_Def_T_T
typedef saCircBuff< int16_t, int16_t, int16_t, saCircBuffCopyByteWise< int16_t >, saCircBuffCopyByteWise< int16_t >, false, false > saCircBuff_16_16_Def_F_F
typedef saCircBuff< int16_t, int16_t, int32_t, saCircBuffCopyByteWise< int16_t >, saCircBuffCopyImplicit< int16_t, int32_t >, true, true > saCircBuff_16_32_Imp_T_T
typedef saCircBuff< int16_t, saSample, int32_t, saCircBuffCopyExplicit< saSample, int16_t, saSampleTo< int16_t > >, saCircBuffCopyImplicit< int16_t, int32_t >, false, true > saCircBuff_16_saSample_32_Exp_F_T
Functions
template<typename C , typename T >
void producer_fn (C &cbuf, binary_semaphore &bs, std::size_t sz, T *inbuf)
template<typename C , typename T >
void consumer_fn (C &cbuf, binary_semaphore &bs, T *outbuf, std::size_t sz, double magic)
void test_instantiation (void)
void test_nullptr (void)
void test_int16_write_and_int16_read (void)
void test_threaded_int16_write_and_int16_read (void)
void test_threaded_int16_write_and_int32_read (void)
void test_threaded_saSample_write_and_int32_read (void)
int main (void)
Typedef Documentation
binary_semaphore
using binary_semaphore = std::counting_semaphore<1>
Definition at line 16 of file saCircBuff_test.cc.
saCircBuff_16_16_Def_T_T
typedef saCircBuff<int16_t, int16_t, int16_t, saCircBuffCopyByteWise<int16_t>, saCircBuffCopyByteWise<int16_t>, true, true> saCircBuff_16_16_Def_T_T
Definition at line 31 of file saCircBuff_test.cc.
saCircBuff_16_16_Def_F_F
typedef saCircBuff<int16_t, int16_t, int16_t, saCircBuffCopyByteWise<int16_t>, saCircBuffCopyByteWise<int16_t>, false, false> saCircBuff_16_16_Def_F_F
Definition at line 40 of file saCircBuff_test.cc.
saCircBuff_16_32_Imp_T_T
typedef saCircBuff<int16_t, int16_t, int32_t, saCircBuffCopyByteWise<int16_t>, saCircBuffCopyImplicit<int16_t,int32_t>, true, true> saCircBuff_16_32_Imp_T_T
Definition at line 49 of file saCircBuff_test.cc.
saCircBuff_16_saSample_32_Exp_F_T
typedef saCircBuff<int16_t, saSample, int32_t, saCircBuffCopyExplicit<saSample,int16_t,saSampleTo<int16_t> >, saCircBuffCopyImplicit<int16_t,int32_t>, false, true> saCircBuff_16_saSample_32_Exp_F_T
Definition at line 58 of file saCircBuff_test.cc.
Function Documentation
producer_fn()
void producer_fn (C & cbuf, binary_semaphore & bs, std::size_t sz, T * inbuf)
Definition at line 61 of file saCircBuff_test.cc.
consumer_fn()
void consumer_fn (C & cbuf, binary_semaphore & bs, T * outbuf, std::size_t sz, double magic)
Definition at line 110 of file saCircBuff_test.cc.
test_instantiation()
void test_instantiation (void)
Definition at line 193 of file saCircBuff_test.cc.
Referenced by main().
test_nullptr()
void test_nullptr (void)
Definition at line 221 of file saCircBuff_test.cc.
References saCircBuff< StoredType, InputType, OutputType, IC, OC, DoOverRunException, DoUnderRunException >::Extract(), and saCircBuff< StoredType, InputType, OutputType, IC, OC, DoOverRunException, DoUnderRunException >::Insert().
Referenced by main().
test_int16_write_and_int16_read()
void test_int16_write_and_int16_read (void)
Definition at line 252 of file saCircBuff_test.cc.
References saCircBuff< StoredType, InputType, OutputType, IC, OC, DoOverRunException, DoUnderRunException >::Clear(), saCircBuff< StoredType, InputType, OutputType, IC, OC, DoOverRunException, DoUnderRunException >::Extract(), and saCircBuff< StoredType, InputType, OutputType, IC, OC, DoOverRunException, DoUnderRunException >::Insert().
Referenced by main().
test_threaded_int16_write_and_int16_read()
void test_threaded_int16_write_and_int16_read (void)
Definition at line 434 of file saCircBuff_test.cc.
Referenced by main().
test_threaded_int16_write_and_int32_read()
void test_threaded_int16_write_and_int32_read (void)
Definition at line 471 of file saCircBuff_test.cc.
Referenced by main().
test_threaded_saSample_write_and_int32_read()
void test_threaded_saSample_write_and_int32_read (void)
Definition at line 508 of file saCircBuff_test.cc.
Referenced by main().
main()
int main (void)
Definition at line 546 of file saCircBuff_test.cc.
References test_instantiation(), test_int16_write_and_int16_read(), test_nullptr(), test_threaded_int16_write_and_int16_read(), test_threaded_int16_write_and_int32_read(), and test_threaded_saSample_write_and_int32_read().