PitchTuner: src/SimpleAudio/saInputStreamFile_test.cc File Reference
saInputStreamFile_test.cc File Reference
#include <iostream>
#include <sstream>
#include <iomanip>
#include <memory>
#include <algorithm>
#include <iterator>
#include "saInputFileSelector.h"
#include "saInputFileWav.h"
#include "saInputFileAscii.h"
#include "saInputStream.h"
Functions
static void Usage ()
static void ParseOptions (int argc, char *argv[], std::string &sourceName, std::size_t &readSize, bool &readSize_set, std::size_t &channel, bool &channel_set, bool &helpReq, bool &read_test, bool &clear_test, bool &eos_test, bool &frames_read_test)
int main (int argc, char *argv[])
Function Documentation
Usage()
static void Usage () static
Definition at line 20 of file saInputStreamFile_test.cc.
Referenced by ParseOptions().
ParseOptions()
static void ParseOptions (int argc, char * argv[], std::string & sourceName, std::size_t & readSize, bool & readSize_set, std::size_t & channel, bool & channel_set, bool & helpReq, bool & read_test, bool & clear_test, bool & eos_test, bool & frames_read_test) static
Definition at line 32 of file saInputStreamFile_test.cc.
References Usage().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 142 of file saInputStreamFile_test.cc.
References ParseOptions(), SimpleAudio::saInputSourceOpenFileAscii(), SimpleAudio::saInputSourceOpenFileWav(), and SimpleAudio::saInputStreamOpenFile().