PitchTuner: src/SimpleAudio/saOutputStreamFile_test.cc File Reference
saOutputStreamFile_test.cc File Reference
#include <vector>
#include <iostream>
#include <sstream>
#include <algorithm>
#include <stdexcept>
#include "saSample.h"
#include "saInputFileSelector.h"
#include "saInputSource.h"
#include "saInputFileWav.h"
#include "saInputFileAscii.h"
#include "saInputStream.h"
#include "saOutputFileSelector.h"
#include "saOutputSink.h"
#include "saOutputStream.h"
#include "saOutputFileWav.h"
Functions
static void Usage ()
void ParseOptions (int argc, char *argv[], bool &helpReq, std::size_t &seconds, std::size_t &framesPerSecond, std::size_t &latencyMs, std::string &inFileName, std::string &inDeviceName, std::string &outFileName, std::string &outDeviceName)
int main (int argc, char *argv[])
Function Documentation
Usage()
static void Usage () static
Definition at line 20 of file saOutputStreamFile_test.cc.
Referenced by ParseOptions().
ParseOptions()
void ParseOptions (int argc, char * argv[], bool & helpReq, std::size_t & seconds, std::size_t & framesPerSecond, std::size_t & latencyMs, std::string & inFileName, std::string & inDeviceName, std::string & outFileName, std::string & outDeviceName)
Definition at line 33 of file saOutputStreamFile_test.cc.
References Usage().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 109 of file saOutputStreamFile_test.cc.
References ParseOptions(), SimpleAudio::saInputSourceOpenFileWav(), SimpleAudio::saInputStreamOpenDevice(), SimpleAudio::saInputStreamOpenFile(), SimpleAudio::saOutputSinkOpenFileWav(), SimpleAudio::saOutputStreamOpenDevice(), and SimpleAudio::saOutputStreamOpenFile().