PitchTuner: ReadFromFile< T > Struct Template Reference
ReadFromFile< T > Struct Template Reference
Public Member Functions
ReadFromFile (const char *source_name)
~ReadFromFile ()
bool is_ok (void)
bool end_of_file (void)
bool read_header (std::size_t *header)
T read ()
Private Attributes
std::ifstream infile
Detailed Description
template<typename T>
struct SimpleAudio::ReadFromFile< T >
Definition at line 30 of file saInputFileAscii.cc.
Constructor & Destructor Documentation
ReadFromFile()
ReadFromFile (const char * source_name) inline
Definition at line 32 of file saInputFileAscii.cc.
References ReadFromFile< T >::infile.
~ReadFromFile()
~ReadFromFile () inline
Definition at line 37 of file saInputFileAscii.cc.
References ReadFromFile< T >::infile.
Member Function Documentation
is_ok()
bool is_ok (void) inline
Definition at line 42 of file saInputFileAscii.cc.
References ReadFromFile< T >::infile.
Referenced by saInputFileAscii::Collect(), and saInputFileAscii::saInputFileAscii().
end_of_file()
bool end_of_file (void) inline
Definition at line 47 of file saInputFileAscii.cc.
References ReadFromFile< T >::infile.
Referenced by saInputFileAscii::EndOfSource().
read_header()
bool read_header (std::size_t * header) inline
Definition at line 52 of file saInputFileAscii.cc.
References ReadFromFile< T >::infile.
Referenced by saInputFileAscii::saInputFileAscii().
read()
T read () inline
Definition at line 60 of file saInputFileAscii.cc.
References ReadFromFile< T >::infile.
Referenced by saInputFileAscii::Collect().
Field Documentation
infile
std::ifstream infile private
Definition at line 65 of file saInputFileAscii.cc.
Referenced by ReadFromFile< T >::end_of_file(), ReadFromFile< T >::is_ok(), ReadFromFile< T >::read(), ReadFromFile< T >::read_header(), ReadFromFile< T >::ReadFromFile(), and ReadFromFile< T >::~ReadFromFile().
The documentation for this struct was generated from the following file:
src/SimpleAudio/saInputFileAscii.cc